# GitHub Actions Workflow para o projeto Finance Tracker
# Este workflow instala dependências, executa testes e faz lint do código Python

name: Finance Tracker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Análise de código com flake8
      run: |
        # Verifica erros críticos de sintaxe e nomes indefinidos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Trata todos os outros avisos como warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Testes com pytest
      run: |
        pytest

    # (Opcional) Salvar artefatos de saída como relatórios .txt ou .json
    - name: Upload de Relatórios (se existirem)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: relatorios
        path: |
          **/*.txt
          **/*.json
